path: /scratch/hekalo/Datasets/vindr/trainval/dicom/
train: images/train
val: images/val
test: images/test
names:
  0: Aortic enlargement
  1: Atelectasis
  2: Calcification
  3: Cardiomegaly
  4: Clavicle fracture
  5: Consolidation
  6: Edema
  7: Emphysema
  8: Enlarged PA
  9: ILD
  10: Infiltration
  11: Lung Opacity
  12: Lung cavity
  13: Lung cyst
  14: Mediastinal shift
  15: No finding
  16: Nodule/Mass
  17: Other lesion
  18: Pleural effusion
  19: Pleural thickening
  20: Pneumothorax
  21: Pulmonary fibrosis
  22: Rib fracture
