path: /scratch/hekalo/Datasets/vindr/dataset/
train: images/train
val: images/val
test: images/test
names:
  0: Aortic enlargement
  1: Atelectasis
  2: Calcification
  3: Cardiomegaly
  4: Clavicle fracture
  5: Consolidation
  6: Edema
  7: Emphysema
  8: Enlarged PA
  9: ILD
  10: Infiltration
  11: Lung Opacity
  12: Lung cavity
  13: Lung cyst
  14: Mediastinal shift
  15: Nodule/Mass
  16: Other lesion
  17: Pleural effusion
  18: Pleural thickening
  19: Pneumothorax
  20: Pulmonary fibrosis
  21: Rib fracture
